### ISSUE TITLE
Improved Command Line Arguments?

### ISSUE THREAD

**Issue by dankirkham** [Keridos/Shape-Builder#58]
Feature Request:

Ability to specify shape parameters from command line instead of having to go through the wizard.

I saw some command line arguments, but they didn't seem to be as robust as I am looking for.

**Comment by MarcelloNicoletti** [comment]
What exactly are you looking for? As it is now you can do everything the wizard does from command line.

**Comment by MarcelloNicoletti** [comment]
For example: If you want to build a circle you need 1 parameter, diameter.
Or if you want to build a cuboid you need 3 parameters, depth, width, and height.

When calling the program you pass parameters in after the program name. 
Eg: `Shape-Builder cuboid 1 2 3` for a cuboid that is 1x2x3.

To see what flags to pass after shape parameters use `Shape-Builder -h`.
These flags are stuff like return home after build, count only, and enderchest refill.

Full setup is like: `Shape-Builder [<shape_name> <shape parameters 1> [2] [3] [4]] [flags separated by spaces]` where Shape-Builder is whatever you have named our code and arguments in square brackets are optional. Note: If you do call with a shape you must use the name and the right number of parameters.

**Comment by dankirkham** [comment]
Ahh! That's exactly what I wanted. I just saw the ones in setFlagsFromCommandLine() and thought those were the only ones. Didn't see the help statement. My mistake. Thanks for the help!

**Comment by MarcelloNicoletti** [comment]
Sure thing! I guess it should be more well known. By the way, those flags don't work unless you do the full command of its shapes and parameters. It's wizard or full command, no I between yet.
